name = "BlockDecomposition"
uuid = "6cde8614-403a-11e9-12f1-c10d0f0caca0"
authors = ["Guillaume Marques", "Vitor Nesello", "François Vanderbeck"]
version = "1.0.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
JuMP = "≥ 0.19.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
